server:
  port: 8083

spring:
  application:
    name: fraud-detection-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sentinelflow
    username: sentinelflow
    password: sentinelflow123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fraud-detection-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

fraud:
  score-threshold: 0.75

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.sentinelflow: DEBUG
