server:
  port: 8080
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: ingestion-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/payments/**
        - id: analytics-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/analytics/**
        - id: fraud-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/fraud/**
        - id: insight-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/insights/**
    discovery:
      enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis123
      connect-timeout: 5000
      timeout: 5000
jwt:
  secret: sentinelflow-dev-secret-key-minimum-256-bits-long-padding-here
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
logging:
  level:
    root: INFO
    com.sentinelflow: DEBUG
